### ISSUE TITLE
Build Number with 2 (or more) decimal points not working

### ISSUE THREAD

**Issue by FBNitro** [gligoran/cordova-set-version#37]
From the CLI (I did not test other means), a build number with multiple decimal points will not update the config.xml.

**Working Example:**
cordova-set-version -v 1.0.2 -b 7.7
**Results:** ios-CFBundleVersion="7.7" version="1.0.2" android-versionCode="7.7" osx-CFBundleVersion="7.7"

**Failing Example:**
cordova-set-version -v 1.0.2 -b 7.7.7
**Results:** No update to the config.xml.  No Error/Warning.  No indication that something has gone wrong.

**Expected:** I'd like it to just update the build version # with my version, or at the very least the cli should provide an error.

**Note:** The ios app store will accept a 7.7.7 as a valid build #.  I don't know if the android-versionCode with decimals is valid.

**Comment by gligoran** [comment]
Actually, this is a bug, because I designed the build number to be an integer. There should be an error if the build number isn't a whole number. The design was done in this way, as [`versionCode` for Android](https://developer.android.com/studio/publish/versioning.html) must be an integer. I will fix the bug I mentioned, but that means no decimal points will be allowed.

If, at some point, storing build number per platforms is implemented, this issue can be revisited.

**Comment by FBNitro** [comment]
Sounds like the appropriate solution. Thanks.
